import { Comfortaa } from "next/font/google";
import "./globals.css";

const comfortaa = Comfortaa({subsets: ["latin"]});

export const metadata = {
  title: "LNBG London Coin - Initial Coin Offering",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={comfortaa.className}>{children}</body>
    </html>
  );
}
