import { Comfortaa } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const comfortaa = Comfortaa({ subsets: ["latin"] });

export const metadata = {
  title: "LNBG London Coin - Initial Coin Offering",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-[url('/bgs/body-bg.png')] ${comfortaa.className}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
